services:
  web:
    image: php:8.2-apache
    container_name: web
    restart: unless-stopped

    ports:
      - "80:80"
      - "8443:443"

    volumes:
      - ./html:/var/www/html:rw
      - ./conf:/etc/apache2/sites-enabled:ro
      - ./logs:/var/log/apache2

    networks:
      - hispalab

    command: >
      /bin/sh -c "
        a2enmod ssl rewrite headers &&
        apache2-foreground
      "

networks:
  hispalab:
    driver: bridge
